#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Shithead.Resource", IsApplication=true)]

namespace Shithead
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int titleText = 2130771968;
			
			// aapt resource value: 0x7f010001
			public const int valueColor = 2130771969;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int aceOfClubs = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int aceOfDiamonds = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int aceOfHearts = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int aceOfSpades = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int back = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int blackJoker = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int eightOfClubs = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int eightOfDiamonds = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int eightOfHearts = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int eightOfSpades = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int fiveOfClubs = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int fiveOfDiamonds = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int fiveOfHearts = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int fiveOfSpades = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int fourOfClubs = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int fourOfDiamonds = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int fourOfHearts = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int fourOfSpades = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int jackOfClubs = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int jackOfDiamonds = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int jackOfHearts = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int jackOfSpades = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int kingOfClubs = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int kingOfDiamonds = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int kingofHearts = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int kingOfSpades = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int nineOfClubs = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int nineOfDiamonds = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int nineOfHearts = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int nineOfSpades = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int queenOfClubs = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int queenOfDiamonds = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int queenOfHearts = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int queenOfSpades = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int redJoker = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int sevenOfClubs = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int sevenOfDiamonds = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int sevenOfHearts = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int sevenOfSpades = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int sixOfClubs = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int sixOfDiamonds = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int sixOfHearts = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int sixOfSpades = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int tenOfClubs = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int tenOfDiamonds = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int tenOfHearts = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int tenOfSpades = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int threeOfClubs = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int threeOfDiamonds = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int threeOfHearts = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int threeOfSpades = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int twoOfClubs = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int twoOfDiamonds = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int twoOfHearts = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int twoOfSpades = 2130837558;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050002
			public const int button1 = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int handView1 = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int mainxaml = 2131034113;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int HandView = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int view_color_options = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int start_game = 2130968577;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] Options = new int[] {
					2130771968,
					2130771969};
			
			// aapt resource value: 0
			public const int Options_titleText = 0;
			
			// aapt resource value: 1
			public const int Options_valueColor = 1;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
